"""Nullable-area Phase A checkpoint: isolated tests or fresh GET-only evidence."""
import copy
import http.client
import importlib.util
import json
import sys
import time
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.dont_write_bytecode = True
sys.path[:0] = [str(ROOT / "scripts"), str(ROOT / "tests")]
spec = importlib.util.spec_from_file_location("recheck", ROOT / "reports/stage73-fresh-recheck-2026-09-09.py")
recheck = importlib.util.module_from_spec(spec)
spec.loader.exec_module(recheck)
STAMP = "2026-09-09-nullable"


def save(name, result):
    with (ROOT / "reports" / f"stage73-{name}-{STAMP}.json").open("x", encoding="utf-8") as handle:
        json.dump(result, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    print(json.dumps(result, ensure_ascii=False), flush=True)


def offline():
    import run_stage73_offline
    digest = recheck.regressions.source_digest()
    original = http.client.HTTPConnection.request
    actual_attempts = []
    def guard(connection, method, path, *args, **kwargs):
        if connection.host not in {"127.0.0.1", "localhost", "::1"}:
            actual_attempts.append(method)
            raise RuntimeError("offline_network_only")
        return original(connection, method, path, *args, **kwargs)
    start = time.perf_counter()
    with patch.object(http.client.HTTPConnection, "request", guard):
        result = unittest.TextTestRunner(verbosity=1).run(unittest.defaultTestLoader.discover(str(ROOT / "tests")))
    save("repository", dict(status="pass" if result.wasSuccessful() and not actual_attempts else "fail",
        source_digest=digest, tests=result.testsRun, failures=len(result.failures), errors=len(result.errors),
        skips=len(result.skipped), failed_tests=[str(t) for t, _ in result.failures + result.errors],
        elapsed_s=round(time.perf_counter() - start, 4), actual_network_attempts=len(actual_attempts),
        HA_POST=sum(m.upper() == "POST" for m in actual_attempts),
        source_unchanged=digest == recheck.regressions.source_digest()))
    with patch.object(http.client.HTTPConnection, "request", guard):
        fake = run_stage73_offline.run()
    fake["source_digest"] = digest
    save("fake-endpoint", fake)


def bindings():
    import bounded_ha_agent as agent
    import canary_contract as contract
    import owner_chat
    import stage73_oracle as oracle
    import websocket
    configured = contract.load_config()
    if configured.control_enabled or configured.canary_live_enabled:
        raise RuntimeError("Phase_A_requires_OFF")
    reader, graph = recheck.reader, recheck.graph
    cfg = reader.AdapterConfig(reader.EXPECTED_SCHEME, reader.EXPECTED_HOST, reader.EXPECTED_PORT,
                               recheck.TOKEN.read_text(encoding="ascii").strip(), (), True)
    # Fixed OWNER selections, not generated by the production resolver. Tuya Local
    # qualifies the private relay binding but cannot qualify its spoken name.
    selected = [
        ("Свет", "кабинет", "switch", None, "Кабинет", "включи свет в кабинете", "plan"),
        ("коридор", "коридор", "switch", None, "Коридор", "включи коридор", "plan"),
        ("ночник Подсветка", "ночник", "light", None, "Кабинет", "включи ночник Подсветка", "plan"),
        ("Вытяжка на кухне", "Вытяжка на кухне", "switch", None, "Кухня", "включи вытяжку на кухне", "plan"),
        ("реле вентилятора", "реле вентилятора", "switch", "tuya_local", "Кабинет", "включи реле вентилятора в кабинете", "clarification"),
    ]
    report = dict(scope="fresh_nullable_contract_only_not_owner_reviewed_acceptance",
        source_digest=recheck.regressions.source_digest(), live_approval=False, live_cycles=0,
        installed_records=len(configured.records), canary_config_installed=contract.CONFIG_PATH.exists(), cases=[])
    with patch.object(http.client.HTTPConnection, "request", recheck.http_guard), patch.object(websocket.WebSocket, "send", recheck.ws_guard):
        document = graph.collect_inventory(cfg)
        before = copy.deepcopy(document)
        parents = {p["target_ref"]: p for p in document["physical_nodes"]}
        records = []
        for i, (name, parent, domain, platform, room, phrase, expected) in enumerate(selected):
            matches = [e for e in document["entities"] if e["display_name"].casefold() == name.casefold()
                and parents[e["target_ref"]]["display_name"].casefold() == parent.casefold()
                and e["domain"] == domain and (platform is None or e["platform"] == platform)
                and not e.get("disabled") and not e.get("hidden")]
            if len(matches) != 1:
                raise RuntimeError("owner_selection_not_unique")
            entity = matches[0]
            if entity["area_ref"] is not None or entity.get("registry_area_unassigned") is not True:
                raise RuntimeError("registry_no_longer_explicitly_unassigned")
            records.append(dict(canary_id=f"owner-selected-{i+1}", target_ref=entity["entity_ref"],
                entity_ref=entity["entity_ref"], entity_id=entity["entity_id"], physical_identity=entity["target_ref"],
                domain=domain, registry_area_ref=None, registry_area=None, owner_area=room,
                allowed_actions=["turn_on", "turn_off"], verification_profile="stable_boolean_state",
                rollback_actions=["turn_on", "turn_off"], allow_noop=True))
        draft = contract.ControlConfig.parse(dict(CONTROL_ENABLED=False, CANARY_LIVE_ENABLED=False,
                                                 owner_approval="", canaries=records))
        # Independent WebSocket reads assert explicit nulls in both raw records.
        private = {r.canary_id: r.entity_id for r in draft.records}
        observed = oracle.read_bindings(cfg.host, cfg.port, cfg.token, private, {k: None for k in private})
        for row, record in zip(selected, draft.records):
            name, parent, domain, platform, room, phrase, expected = row
            contract.binding_fingerprint(document, record, "turn_on")
            captured = []
            def core(question, context, history, **kwargs):
                result = agent.process_turn(question, context, history, inventory_loader=lambda: document,
                    control_config_loader=lambda: draft, trace_sink=None)
                captured.append(result)
                return result.answer
            context = owner_chat.startup_context()
            context["control_request_key"] = f"nullable-shadow-{time.time_ns()}"
            start = time.perf_counter()
            answer = owner_chat.answer_natural(phrase, context, [], natural_agent=core)
            result = captured[0]
            outcome = "plan" if result.canary_plan else "clarification" if result.frame.kind == "clarification" else "no_canary_plan"
            report["cases"].append(dict(utterance=phrase, expected_human_target=name, expected_owner_area=room,
                expected_outcome=expected, actual_outcome=outcome, registry_area=record.registry_area,
                independent_registry_assertion=record.canary_id in observed,
                selected_human_target=result.action_plan.target_label if result.action_plan else None,
                plan_owner_area=result.canary_plan.owner_area if result.canary_plan else None,
                receipt_status=result.action_receipt.status if result.action_receipt else None,
                service_calls=result.action_receipt.service_calls if result.action_receipt else 0,
                correct_private_target=(result.canary_plan.resolved_target_ref == record.target_ref) if result.canary_plan else None,
                pass_case=outcome == expected and (not result.canary_plan or result.canary_plan.resolved_target_ref == record.target_ref),
                latency_s=round(time.perf_counter() - start, 4), answer=answer))
        report.update(metadata_unchanged=document == before, owner_records_validated=len(draft.records),
            flags_off=not draft.control_enabled and not draft.canary_live_enabled,
            network=dict(recheck.network), private_config_persisted=False,
            status="pass" if all(c["pass_case"] for c in report["cases"]) else "fail")
    save("nullable-bindings", report)


if __name__ == "__main__":
    if sys.argv[1:] == ["offline"]:
        offline()
    elif sys.argv[1:] == ["live-read"]:
        recheck.STAMP = STAMP
        raise SystemExit(recheck.run())
    elif sys.argv[1:] == ["bindings"]:
        bindings()
    else:
        raise SystemExit("choose offline / live-read / bindings; no live-control mode exists")
